parameters:
    oro_action.assembler.operation.class: Oro\Bundle\ActionBundle\Model\Assembler\OperationAssembler
    oro_action.assembler.action_group.class: Oro\Bundle\ActionBundle\Model\Assembler\ActionGroupAssembler
    oro_action.assembler.argument.class: Oro\Bundle\ActionBundle\Model\Assembler\ArgumentAssembler
    oro_action.assembler.operation_action_group.class: Oro\Bundle\ActionBundle\Model\Assembler\OperationActionGroupAssembler
    oro_action.assembler.attribute.class: Oro\Bundle\ActionBundle\Model\Assembler\AttributeAssembler
    oro_action.assembler.form_options.class: Oro\Bundle\ActionBundle\Model\Assembler\FormOptionsAssembler

services:
    oro_action.assembler.operation:
        class: %oro_action.assembler.operation.class%
        arguments:
            - @oro_action.function_factory
            - @oro_action.expression.factory
            - @oro_action.assembler.attribute
            - @oro_action.assembler.form_options
            - @oro_action.assembler.operation_action_group
            - @oro_entity.doctrine_helper

    oro_action.assembler.action_group:
        class: %oro_action.assembler.action_group.class%
        arguments:
            - @oro_action.function_factory
            - @oro_action.expression.factory
            - @oro_action.assembler.argument
            - @oro_entity.doctrine_helper

    oro_action.assembler.argument:
        class: %oro_action.assembler.argument.class%

    oro_action.assembler.operation_action_group:
        class: %oro_action.assembler.operation_action_group.class%
        arguments: [@oro_action.configuration_pass.replace_property_path]

    oro_action.assembler.attribute:
        class: %oro_action.assembler.attribute.class%
        arguments:
            - @oro_action.attribute_guesser

    oro_action.assembler.form_options:
        class: %oro_action.assembler.form_options.class%
        calls:
            - [addConfigurationPass, [@oro_action.configuration_pass.replace_property_path]]
