parameters:
    oro_action.configuration.config.operation_list.class: Oro\Bundle\ActionBundle\Configuration\OperationListConfiguration
    oro_action.configuration.config.action_group_list.class: Oro\Bundle\ActionBundle\Configuration\ActionGroupListConfiguration
    oro_action.configuration.validator.action_definition.class: Oro\Bundle\ActionBundle\Configuration\ActionDefinitionConfigurationValidator
    oro_action.configuration.provider.class: Oro\Bundle\ActionBundle\Configuration\ConfigurationProvider
    oro_action.configuration_pass.replace_property_path.class: Oro\Bundle\ActionBundle\Model\ConfigurationPass\ReplacePropertyPath

services:
    oro_action.configuration.config.operation_list:
        class: %oro_action.configuration.config.operation_list.class%

    oro_action.configuration.config.action_group_list:
        class: %oro_action.configuration.config.action_group_list.class%

    oro_action.configuration.validator.action_definition:
        class: %oro_action.configuration.validator.action_definition.class%
        arguments:
            - @router
            - @twig.loader
            - @oro_entity.doctrine_helper
            - @logger
            - %kernel.debug%

    oro_action.configuration.provider.operations:
        class: %oro_action.configuration.provider.class%
        arguments:
            - @oro_action.configuration.config.operation_list
            - @oro_action.configuration.validator.action_definition
            - @oro_action.cache.provider.operations
            - []
            - %kernel.bundles%
            - 'operations'

    oro_action.configuration.provider.action_groups:
        class: %oro_action.configuration.provider.class%
        arguments:
            - @oro_action.configuration.config.action_group_list
            - @oro_action.configuration.validator.action_definition
            - @oro_action.cache.provider.action_groups
            - []
            - %kernel.bundles%
            - 'action_groups'

    oro_action.configuration_pass.replace_property_path:
        class: %oro_action.configuration_pass.replace_property_path.class%
        arguments:
            - "data"
