parameters:
    oro_action.handler.delete.class: Oro\Bundle\ActionBundle\Handler\DeleteHandler
    oro_action.helper.context.class: Oro\Bundle\ActionBundle\Helper\ContextHelper
    oro_action.helper.applications.class: Oro\Bundle\ActionBundle\Helper\ApplicationsHelper
    oro_action.helper.restrict.class: Oro\Bundle\ActionBundle\Helper\RestrictHelper
    oro_action.operation_registry.class: Oro\Bundle\ActionBundle\Model\OperationRegistry
    oro_action.action_group_registry.class: Oro\Bundle\ActionBundle\Model\ActionGroupRegistry
    oro_action.manager.class: Oro\Bundle\ActionBundle\Model\ActionManager
    oro_action.assembler.operation.class: Oro\Bundle\ActionBundle\Model\Assembler\OperationAssembler
    oro_action.assembler.action_group.class: Oro\Bundle\ActionBundle\Model\Assembler\ActionGroupAssembler
    oro_action.assembler.argument.class: Oro\Bundle\ActionBundle\Model\Assembler\ArgumentAssembler
    oro_action.assembler.operation_action_group.class: Oro\Bundle\ActionBundle\Model\Assembler\OperationActionGroupAssembler
    oro_action.assembler.attribute.class: Oro\Bundle\ActionBundle\Model\Assembler\AttributeAssembler
    oro_action.attribute_guesser.class: Oro\Bundle\ActionBundle\Model\AttributeGuesser
    oro_action.assembler.form_options.class: Oro\Bundle\ActionBundle\Model\Assembler\FormOptionsAssembler
    oro_action.form_manager.class: Oro\Bundle\ActionBundle\Model\ActionFormManager
    oro_action.api_manager.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_action.datagrid.action_extension.class: Oro\Bundle\ActionBundle\Datagrid\Extension\ActionExtension
    oro_action.datagrid.action.action_widget_action.class: Oro\Bundle\ActionBundle\Datagrid\Action\ActionWidgetAction
    oro_action.datagrid.mass_action_provider.registry.class: Oro\Bundle\ActionBundle\Datagrid\Provider\MassActionProviderRegistry
    oro_action.layout.block_type.action_line_buttons.class: Oro\Bundle\ActionBundle\Layout\Block\Type\ActionLineButtonsType
    oro_action.layout.block_type.action_combined_buttons.class: Oro\Bundle\ActionBundle\Layout\Block\Type\ActionCombinedButtonsType
    oro_action.layout.data_provider.actions_data_rpovider.class: Oro\Bundle\ActionBundle\Layout\DataProvider\ActionsDataProvider

services:
    oro_action.handler.delete:
        class: %oro_action.handler.delete.class%
        arguments:
            - @oro_soap.handler.delete
            - @oro_action.api_manager
            - @oro_entity.doctrine_helper

    oro_action.helper.context:
        class: %oro_action.helper.context.class%
        arguments:
            - @oro_entity.doctrine_helper
            - @property_accessor
            - @request_stack

    oro_action.helper.applications:
        class: %oro_action.helper.applications.class%
        arguments:
            - @security.token_storage

    oro_action.helper.restrict:
        class: %oro_action.helper.restrict.class%

    oro_action.operation_registry:
        class: %oro_action.operation_registry.class%
        arguments:
            - @oro_action.configuration.provider
            - @oro_action.assembler.operation
            - @oro_action.helper.applications

    oro_action.action_group_registry:
        class: %oro_action.action_group_registry.class%
        arguments:
            - @oro_action.configuration.provider
            - @oro_action.assembler.action_group

    oro_action.manager:
        class: %oro_action.manager.class%
        arguments:
            - @oro_action.operation_registry
            - @oro_entity.doctrine_helper
            - @oro_action.helper.context

    oro_action.assembler.operation:
        class: %oro_action.assembler.operation.class%
        arguments:
            - @oro_action.action_factory
            - @oro_action.expression.factory
            - @oro_action.assembler.attribute
            - @oro_action.assembler.form_options
            - @oro_action.assembler.operation_action_group
            - @oro_entity.doctrine_helper

    oro_action.assembler.action_group:
        class: %oro_action.assembler.action_group.class%
        arguments:
            - @oro_action.action_factory
            - @oro_action.expression.factory
            - @oro_action.assembler.argument

    oro_action.assembler.argument:
        class: %oro_action.assembler.argument.class%

    oro_action.assembler.operation_action_group:
        class: %oro_action.assembler.operation_action_group.class%

    oro_action.assembler.attribute:
        class: %oro_action.assembler.attribute.class%
        arguments:
            - @oro_action.attribute_guesser

    oro_action.attribute_guesser:
        class: %oro_action.attribute_guesser.class%
        arguments:
            - @form.registry
            - @doctrine
            - @oro_entity_config.provider.entity
            - @oro_entity_config.provider.form
        calls:
            # mapping from doctrine type to attribute parameters
            - [addDoctrineTypeMapping, ["string", "string"]]
            - [addDoctrineTypeMapping, ["integer", "integer"]]
            - [addDoctrineTypeMapping, ["smallint", "integer"]]
            - [addDoctrineTypeMapping, ["bigint", "integer"]]
            - [addDoctrineTypeMapping, ["boolean", "boolean"]]
            - [addDoctrineTypeMapping, ["decimal", "float"]]
            - [addDoctrineTypeMapping, ["date", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["time", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["datetime", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["datetimetz", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["text", "string"]]
            - [addDoctrineTypeMapping, ["array", "array"]]
            - [addDoctrineTypeMapping, ["simple_array", "array"]]
            - [addDoctrineTypeMapping, ["json_array", "array"]]
            - [addDoctrineTypeMapping, ["float", "float"]]
            - [addDoctrineTypeMapping, ["guid", "string"]]
            # custom types
            - [addDoctrineTypeMapping, ["percent", "float"]]
            - [addDoctrineTypeMapping, ["money", "float"]]
            # mapping from attribute type to form parameters
            - [addFormTypeMapping, ["string", "text"]]
            - [addFormTypeMapping, ["int", "integer", { precision: 0 }]]
            - [addFormTypeMapping, ["integer", "integer", { precision: 0 }]]
            - [addFormTypeMapping, ["bool", "checkbox"]]
            - [addFormTypeMapping, ["boolean", "checkbox"]]
            - [addFormTypeMapping, ["float", "number"]]

    oro_action.assembler.form_options:
        class: %oro_action.assembler.form_options.class%
        calls:
            - [addConfigurationPass, [@oro_action.configuration_pass.replace_property_path]]

    oro_action.form_manager:
        class: %oro_action.form_manager.class%
        arguments:
            - @form.factory
            - @oro_action.manager
            - @oro_action.helper.context

    oro_action.api_manager:
        class: %oro_action.api_manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - ''
            - @doctrine.orm.entity_manager

    oro_action.datagrid.extension.action:
        class: %oro_action.datagrid.action_extension.class%
        arguments:
            - @oro_action.manager
            - @oro_action.helper.context
            - @oro_action.helper.applications
            - @oro_action.datagrid.mass_action_provider.registry
        calls:
            - [setActionGroups, [['', 'datagridRowAction']]]
        tags:
            - { name: oro_datagrid.extension }
        lazy: true

    oro_action.datagrid.action.action_widget_action:
        class: %oro_action.datagrid.action.action_widget_action.class%
        arguments:
            - @translator
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.action.type, type: action-widget }

    oro_action.datagrid.mass_action_provider.registry:
        class: %oro_action.datagrid.mass_action_provider.registry.class%

    oro_action.layout.block_type.action_line_buttons:
        class: %oro_action.layout.block_type.action_line_buttons.class%
        arguments:
            - @oro_action.helper.applications
            - @oro_entity.doctrine_helper
        tags:
            - { name: layout.block_type, alias: action_line_buttons }

    oro_action.layout.block_type.action_combined_buttons:
        class: %oro_action.layout.block_type.action_combined_buttons.class%
        tags:
            - { name: layout.block_type, alias: action_combined_buttons }

    oro_action.layout.data_provider.actions_data_rpovider:
        class: %oro_action.layout.data_provider.actions_data_rpovider.class%
        arguments:
            - @oro_action.manager
            - @oro_action.helper.restrict
            - @translator
            - @oro_action.helper.context
        tags:
            - { name: layout.data_provider, alias: actions }
