workflows:
    workflow_test_bap_12413:
        entity: Oro\Bundle\ProductBundle\Entity\Product
        entity_attribute: entity
        steps:
            'step_start_1':
                allowed_transitions:
                    - transition_start1
                    - transition_start2
            step_final:
                allowed_transitions: {  }
        transitions:
            transition_start1:
                display_type: dialog
                step_to: step_final
                is_start: true
                transition_definition: transition_start1_definition
                frontend_options:
                    icon: 'yahoo'
                    class: 'start1'
                form_type: oro_workflow_transition
                init_routes:
                    - oro_user_view #/view/{id}
                    - oro_customer_frontend_account_user_profile #account/profile/
            transition_start2:
                display_type: dialog
                step_to: step_final
                is_start: true
                transition_definition: transition_start2_definition
                frontend_options:
                    icon: 'yahoo'
                    class: 'start1'
                form_type: oro_workflow_transition
                init_entities:
                    - 'Oro\Bundle\SaleBundle\Entity\Quote' #oro_sale_quote_view or admin/sale/quote/view/1
        attributes: {  }
        transition_definitions:
            transition_start1_definition:
                preactions: ~
                preconditions:
#                    '@equals': [true, false]
                conditions: ~
                actions:
                    - '@assign_value': [$.entity.sku, '34234234']
                    - '@flush_entity': $.entity
                    - '@redirect':
                        route: oro_product_view
                        route_parameters:
                            id: $.entity.id

            transition_start2_definition:
                preactions: ~
                preconditions:
#                    '@equals': [true, false]
                conditions: ~
                actions:
                    - '@assign_value': [$.entity.sku, 'wwww234234www']
                    - '@flush_entity': $.entity
                    - '@redirect':
                        route: oro_product_view
                        route_parameters:
                            id: $.entity.id
        entity_restrictions: {  }
